require('general.config')
require('utils.packer')
require('general.keymap')
require('general.theme')
require('general.line')
require('utils.betterment')
require('utils.lsp')
require('utils.compe')
require('utils.lspextra')
-- require('utils.telescope')
require('utils.formatter')
