#!/bin/sh
# Install all dotfiles into the home directory
# Based on: https://github.com/MikeMcQuaid/dotfiles/blob/master/script/setup

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)
git submodule init && git submodule update

for DOTFILE in *; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  echo $DOTFILE | egrep -q '(^nvim/$|^script/$|\.txt$|\.md$)' && continue

  echo $DOTFILE | grep -q '\.sh' &&
       HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.sh//')"

  if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
  then
    ln -sfv "$DIRFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE"
    ln -sv "$DIRFILE" "$HOMEFILE"
  fi
done

# Configure neovim
NVIM_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvim"
VIM_PLUG="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim"
ln -sfv "$DOTFILESDIR/nvim" "${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
mkdir -p $(dirname "$VIM_PLUG")
rm "$VIM_PLUG"
ln -sv "$DOTFILESDIR/nvim/plug.vim" "$VIM_PLUG"
which nvim && nvim +PlugInstall
